### ISSUE TITLE
Thoughts on requiring JSDoc comments?

### ISSUE THREAD

**Issue by sandersky** [ciena-frost/eslint-config-frost-standard#28]
I'd really like to see us add the following rule:

```json
{
  "rules": {
    "require-jsdoc": 2
  }
}
```

**Comment by job13er** [comment]
You might be able to add that to an individual project, but not likely to be approved here, since the majority voted *against* enforcing jsdoc on every function :(

**Comment by sglanzer** [comment]
Poke me if you want to discuss, I was the main driver behind not enforcing this
