### ISSUE TITLE
Consider adding the "mocha/no-mocha-arrows": 2 rule as an error to `eslintrc.json`

### ISSUE THREAD

**Issue by juwara0** [ciena-frost/eslint-config-frost-standard#37]
We should consider adding the `"mocha/no-mocha-arrows": 2` rule to the https://github.com/ciena-frost/eslint-config-frost-standard/blob/master/eslintrc.json

Here is what this rule does: https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/docs/rules/no-mocha-arrows.md#disallow-arrow-functions-as-arguments-to-mocha-functions-no-mocha-arrows

**Comment by juwara0** [comment]
@sglanzer, @job13er, @notmessenger - Thoughts?

**Comment by job13er** [comment]
I have no problem adding that. I'm already using it on al my projects.

**Comment by sglanzer** [comment]
Makes sense to me
