### ISSUE TITLE
Consider adding the "mocha/valid-test-description": 1 rule as a warning to `eslintrc.json`

### ISSUE THREAD

**Issue by juwara0** [ciena-frost/eslint-config-frost-standard#38]
We should consider adding the "mocha/valid-test-description": 1  rule to the https://github.com/ciena-frost/eslint-config-frost-standard/blob/master/eslintrc.json

Here is what this rule does: https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/docs/rules/valid-test-description.md#match-test-descriptions-against-a-pre-configured-regular-expression-valid-test-description

**Comment by juwara0** [comment]
@sglanzer, @job13er, @notmessenger - Thoughts?

**Comment by job13er** [comment]
I'd make it an error and just do a major bump. I already use that one on all my projects.

**Comment by sglanzer** [comment]
Sure - error + major - headed into an LTS anyway
